FROM ubuntu
MAINTAINER theshubhamgour
RUN apt-get upgrade -y && apt-get update -y
RUN apt-get install git -y && apt-get install maven -y && apt install openjdk-17-jdk -y && apt install openjdk-17-jre
CMD ["echo","Completed"]
